### PR TITLE
Fix Workflow and update README

### PR DESCRIPTION
**Pull request by iAkashPattnaik**
- update `readme.md`
- add `development` section to readme
- fix `workflow` issue

### CODE REVIEW

**Comment by jagadish-pattanaik** [comment]
All checks have failed
1 failing check
Dart / build (pull_request) Failing after 12s — build

**Comment by iAkashPattnaik** [comment]
Oh, i added flutter command to dart worklow.

**Comment by jagadish-pattanaik** [comment]
deleted pubspec.lock?

**Comment by iAkashPattnaik** [comment]
> deleted pubspec.lock?

Yeah, that `pub` generated file. No need for end-users to see.

**Comment by jagadish-pattanaik** [comment]
All checks have failed
1 failing check
Flutter Analyze / build (pull_request) Failing after 1m — build

**Comment by jagadish-pattanaik** [comment]
All checks have failed
1 failing check
Flutter Analyze / build (pull_request) Failing after 1m — build

**Comment by iAkashPattnaik** [comment]
merge it, it will work...

**Comment by jagadish-pattanaik** [comment]
not working, fix it and create a new pull request, also add greetings, labeler, manual workflow, and stale workflows.

**Comment by iAkashPattnaik** [comment]
okay

**Pull request merged**
